### ISSUE TITLE
can I use this in api 15?

### ISSUE THREAD

**Issue by heroddaji** [stepstone-tech/android-material-app-rating#10]
I try your lib, and my min sdk target is 15, while your lib is 16.
Is there any problem if use in api 15?

**Comment by pglebocki** [comment]
Hi,

Probably there should be not big problem, I will try decrease API Level to
14 and then release app if there would be no problems.

2017-07-14 7:00 GMT+02:00 dai tran <notifications@github.com>:

**Comment by pglebocki** [comment]
Hi,

I decreased to API 14 and released version 1.2.0 of app rating library. You
can try it.

Best Regards,
Piotr

2017-07-14 8:48 GMT+02:00 Piotr Głębocki <pglebocki@gmail.com>:

**Comment by heroddaji** [comment]
Awesome, thank you
