### ISSUE TITLE
default EditText color

### ISSUE THREAD

**Issue by anastr** [stepstone-tech/android-material-app-rating#13]
the default EditText background color is white !
it is annoying when i have dark theme (`commentBackgroundColorResId` and `commentTextColorResId` is white!!)

**Comment by pglebocki** [comment]
Hi Anastr,

Thank You very much for feedback.
I will change it in next release (1.3). Edit text background color will inherit from theme's "colorAccent" by default, so it is not be white anymore.
For now you can set properties programically by "setCommentTextColor" and "setCommentBackgroundColor "

BR,
Piotr

**Comment by anastr** [comment]
looks great.
i suggest to add `setCommentHintText(String/ res)` method, it will be nice.

**Comment by pglebocki** [comment]
We released version 2.0.
It contains fixed for this issue and additionally has api for customise hints.
