### ISSUE TITLE
Add neutral button

### ISSUE THREAD

**Issue by defio** [stepstone-tech/android-material-app-rating#19]
Hi, I would like to contribute to your project by adding a neutral button.

It would be useful, for example, to show a "later" button.
Can I submit a pull to request?

![screenshot-1505222113243](https://user-images.githubusercontent.com/6303224/30327766-8bf2ca4a-97cd-11e7-8fb4-9fef63cbfa2d.png)

**Comment by pglebocki** [comment]
Hi @defio 
Looks like good idea. We will verify it and I will check your pull request.
Thanks for contribution

**Comment by pglebocki** [comment]
"Neutral button" feature were merged. Will be added to release 2.1.0
