### ISSUE TITLE
Change Stars Color

### ISSUE THREAD

**Issue by LaTecnologia24** [stepstone-tech/android-material-app-rating#21]
I have see the stars use accentcolor of theme but if i need to change only stars color without change accentcolor of theme?

**Comment by pglebocki** [comment]
Hello @LaTecnologia24,

Currently star's color is associated with accent color. We will consider to define star color as separated attribute and maybe put it in next release. I will inform You if we would add it.

Best regards,
Piotr

**Comment by LaTecnologia24** [comment]
Thanks so much, great work =)

**Comment by pglebocki** [comment]
Dear @LaTecnologia24 ,

We release version 2.1.0. You have api for changing star color
