### ISSUE TITLE
Add change font style

### ISSUE THREAD

**Issue by EstebanC02** [stepstone-tech/android-material-app-rating#22]
Because multiple applications use a proprietary or branded font. Could this type of font be implemented in Rating Dialog?

**Comment by pglebocki** [comment]
Hello @EstebanC02 

Currently our Rating Dialog uses default android font, but this is good point to allow customised fonts. We will consider to added font properties in next release.

**Comment by pglebocki** [comment]
Dear @EstebanC02 ,

We released version 2.1.0. There are added custom styles for each text view (title, description, notes, comment) Refer to "styles" in READEME. You can set any custom font you want.
