### ISSUE TITLE
 android.content.res.Resources$NotFoundException: File res/drawable/edit_text_background.xml from drawable resource ID     ( On  Abdroid 4)

### ISSUE THREAD

**Issue by abedi-reza** [stepstone-tech/android-material-app-rating#28]
Make sure these boxes are checked before submitting your issue - thank you!

- [ ] Check in the issue tracker whether
      this issue wasn't already reported.
- [ ] If it's a bug report check that clear **steps to reproduce**,
**stacktrace**, **expected behaviour** and other needed details are provided.
- [ ] Feature requests contain a **description** of the feature
you're requesting as well as a brief **scenario** explaining
under what circumstances this might be useful.

**Comment by pglebocki** [comment]
@abedi-reza Thanks for reporting
Fixed in release 2.1.1
