### ISSUE TITLE
Default comment text

### ISSUE THREAD

**Issue by acollazog11** [stepstone-tech/android-material-app-rating#30]
if I want to use AppRatingDialog to edit an user review, i can't set the previous user comment.

**Comment by pglebocki** [comment]
Hello @acollazog11 

Currently we do not expose any method to pre fill user comments, but actually this is good use case for implementing it. We will add #setDefaultComment method in next small release, soon.

BR,
Piotr

**Comment by pglebocki** [comment]
Dear @acollazog11 

We just released version 2.2.0. There is method "setDefaultComment" which can pre fill your dialog with given comment text. You can use it for edit mode, now.

BR,
Piotr
