### ISSUE TITLE
Auto-hide the keyboard

### ISSUE THREAD

**Issue by kostasoft** [stepstone-tech/android-material-app-rating#32]
Hello!
On older versions of operating systems (and small screens), the keyboard covers the "Send" and "Cancel" buttons. How can I hide the keyboard, for example, when I click outside the Comment field?

**Comment by RobertZagorski** [comment]
Hello @kostasoft,
Thank You for putting the attention on such case. Yes it happens, that the dialog is partially covered by system keyboard.
However there seems to be an easy solution. Default system keyboard behaviour is reacting for system "Back" button. Keyboard hides, without modifying views state.
Is clicking back button sufficient solution for you in such case?

**Comment by REPTILEHAUS** [comment]
@RobertZagorski  also coming accross this issue in a simulator, I guess its not such good UX to have to rely on the user clicking the back button just to leave a review, its adding another hurdle for them to do an action which is of no benefit to them but maximum benefit to us. If it impedes that end result then by its very nature this awesome plugin has a problem
