### ISSUE TITLE
How to set dialog setCanceledOnTouchOutside

### ISSUE THREAD

**Issue by quantran141** [stepstone-tech/android-material-app-rating#37]
Hi,

Do we have any function like setCanceledOnTouchOutside(false) or something like that ?

**Comment by pglebocki** [comment]
Hi @quantran141 ,
No, actually there is nothing like that, however it seems to be reasonable to have such method.
We will consider to implement that in next release.

Best regards,
Piotr

**Comment by pglebocki** [comment]
Release 2.3.0 available
It has new api for handling cancelation

**Comment by quantran141** [comment]
awesome, thanks Piotr
