### ISSUE TITLE
Hide feedback text field

### ISSUE THREAD

**Issue by Kamil93** [stepstone-tech/android-material-app-rating#41]
Hello would like to display only stars form. How to achieve it?

**Comment by Kamil93** [comment]
I mean only title & stars bar & buttons to accept or cancel. Just without comment field.

**Comment by pglebocki** [comment]
No it is not possible for now. Comment field is always visible by default. 
However this use case should be also handled. We will add disabling comment box possibility in next library release.

**Comment by pglebocki** [comment]
Implemented for 2.3.0. 
Will be released soon

**Comment by pglebocki** [comment]
Release 2.3.0 available
