### ISSUE TITLE
Set default rating to zero

### ISSUE THREAD

**Issue by arunjish** [stepstone-tech/android-material-app-rating#56]
App crashing when default rating is set to zero

**Comment by hamzabinamin** [comment]
@arunjish were you able to find a fix for it? Is there a way to set the default rating to nothing?

**Comment by pglebocki** [comment]
Fixed in  v2.3.1

**Comment by hamzabinamin** [comment]
@pglebocki  Great, however I have noticed that as soon as I update to 2.3.1 my build fails and I get the following in the logs

```
AGPBI: {"kind":"error","text":"error: resource android:attr/dialogCornerRadius not found.","sources":[{"file":"C:\\Users\\Hamza\\.gradle\\caches\\transforms-1\\files-1.1\\appcompat-1.0.0-beta01.aar\\81c825642efea63bb3fc4dbcbfb0947f\\res\\values-v28\\values-v28.xml","position":{"startLine":8,"startColumn":4,"startOffset":447,"endLine":11,"endColumn":12,"endOffset":684}}],"original":"","tool":"AAPT"}
AGPBI: {"kind":"error","text":"error: resource android:attr/dialogCornerRadius not found.","sources":[{"file":"G:\\AndroidStudioProjects\\Activetoo\\app\\build\\intermediates\\incremental\\mergeDebugResources\\merged.dir\\values-v28\\values-v28.xml","position":{"startLine":10}}],"original":"","tool":"AAPT"}
AGPBI: {"kind":"error","text":"error: resource android:attr/fontVariationSettings not found.","sources":[{"file":"C:\\Users\\Hamza\\.gradle\\caches\\transforms-1\\files-1.1\\appcompat-v7-27.1.1.aar\\535085ab54540bc4ec436d9282b78063\\res\\values\\values.xml","position":{"startLine":250,"startColumn":4,"startOffset":27058,"endColumn":68,"endOffset":27122}}],"original":"","tool":"AAPT"}
AGPBI: {"kind":"error","text":"error: resource android:attr/ttcIndex not found.","sources":[{"file":"C:\\Users\\Hamza\\.gradle\\caches\\transforms-1\\files-1.1\\appcompat-v7-27.1.1.aar\\535085ab54540bc4ec436d9282b78063\\res\\values\\values.xml","position":{"startLine":250,"startColumn":4,"startOffset":27058,"endColumn":68,"endOffset":27122}}],"original":"","tool":"AAPT"}
:app:processDebugResources
```

Upon searching it seems like there's an issue with one of the xml files. Could you check that?

I'm sure its not my code, as when I downgrade to 2.3.0 the build succeeds.

**Comment by pglebocki** [comment]
@hamzabinamin there was one additional commit when i updated sdk 
- ANDROID_API_LEVEL=28
- ANDROID_BUILD_TOOLS_VERSION=28.0.3
and migrated support lib to AndroidX.

Can you let me know what is you project setup  (api level target/compile, build tools ) ?

**Comment by hamzabinamin** [comment]
@pglebocki 

- Compiled SDK: 27

- Target SDK: 27

- Min. SDK: 17

- Build Tools: 27.1.1

**Comment by pglebocki** [comment]
could You please update this to api 28
and build tools 28.0.3
and see if it would work ?

**Comment by hamzabinamin** [comment]
Now I get a migration error
```
Manifest merger failed : Attribute application@appComponentFactory value=(android.support.v4.app.CoreComponentFactory) from [com.android.support:support-compat:28.0.0] AndroidManifest.xml:22:18-91
	is also present at [androidx.core:core:1.0.0-beta01] AndroidManifest.xml:22:18-86 value=(androidx.core.app.CoreComponentFactory).
	Suggestion: add 'tools:replace="android:appComponentFactory"' to <application> element at AndroidManifest.xml:18:5-112:19 to override.
```

Seems like this is because of Androidx, is it possible for you to make a release without it?

**Comment by pglebocki** [comment]
What if You put `tools:replace="android:appComponentFactory` in your Manifest like log message suggest

**Comment by hamzabinamin** [comment]
@pglebocki It cleared that error but now I get this 

`error: incompatible types: android.support.v4.app.FragmentActivity cannot be converted to androidx.fragment.app.FragmentActivity`

**Comment by hamzabinamin** [comment]
@pglebocki would it be possible to add a release without androidx. I'm really close to release, wouldn't want to change everything at the moment. Would appreciate a lot.

**Comment by pglebocki** [comment]
@hamzabinamin 
I will not revert back AndroidX, however I can create hotfix branch from previeous state (without androidx) apply fix and make snapshop build to not block You

**Comment by hamzabinamin** [comment]
@pglebocki ok thank you, would I need to downgrade to 2.3.0 for this?

**Comment by pglebocki** [comment]
@hamzabinamin 
Please try v.2.3.0.1 - container hotifx for 0 rating
implementation 'com.stepstone.apprating:app-rating:2.3.0.1'

**Comment by hamzabinamin** [comment]
@pglebocki thanks a lot. It works. Cheers!
