### ISSUE TITLE
Possible to set default rating to nothing?

### ISSUE THREAD

**Issue by hamzabinamin** [stepstone-tech/android-material-app-rating#59]
I want to be able to set the default rating to nothing, so none of the stars get selected by default. Is there a way to do it? @fabiozo @marlonbosse @defio @pglebocki @tommywo

**Comment by pglebocki** [comment]
Hi @hamzabinamin 
You can use `setDefaultRating(0)` for that purpose.
However there is bug ( #56 ) and crash occur when setting to zero 
We will try to fix this soon.

BR,
Piotr

**Comment by hamzabinamin** [comment]
@pglebocki Yes I have noticed the crash as well. Is there any quick fix for this? I really need to push this in production for my app.

**Comment by pglebocki** [comment]
Ok, understand.
I will try to make quick fix today

**Comment by hamzabinamin** [comment]
@pglebocki  thank you so much

**Comment by hamzabinamin** [comment]
@pglebocki I noticed you left a few new commits, did it get fixed? Should I wait for the release version?

**Comment by pglebocki** [comment]
@hamzabinamin 
the fix is released :)
please updated to version v2.3.1

**Comment by hamzabinamin** [comment]
@pglebocki left a comment for you in the other thread, there seems to be an issue with some xml files in the new release version. Thanks again for the quick turnaround.
