### ISSUE TITLE
Manifest merger failed : Attribute application@appComponentFactory value=(android.support.v4.app.CoreComponentFactory) from [com.android.support:support-compat:28.0.0] AndroidManifest.xml:22:18-91 	is also present at [androidx.core:core:1.0.0-beta01] AndroidManifest.xml:22:18-86 value=(androidx.core.app.CoreComponentFactory). 	Suggestion: add 'tools:replace="android:appComponentFactory"' to <application> element at AndroidManifest.xml:20:5-136:19 to override.

### ISSUE THREAD

**Issue by UmarRajput** [stepstone-tech/android-material-app-rating#62]
Hi,
I just import this library, and facing this issue on project build. Can you tell me whats happening ?.
This library only support androidX??

**Comment by zawadz88** [comment]
Hi,
Yes, the current version supports AndroidX. See #61 
I think that the last version pre-AndroidX is 2.3.0: https://github.com/stepstone-tech/android-material-app-rating/compare/v2.3.0...v2.3.1

**Comment by UmarRajput** [comment]
Hi zawadz88,
Thank you.
By using v2.3.0 the issue has resolved. v2.3.1 only supports AndroidX.
