### ISSUE TITLE
JCenter is deprecated

### ISSUE THREAD

**Issue by aenonGit** [stepstone-tech/android-material-app-rating#69]
Make sure these boxes are checked before submitting your issue - thank you!

- [x] Check in the issue tracker whether
      this issue wasn't already reported.
- [x] If it's a bug report check that clear **steps to reproduce**,
**stacktrace**, **expected behaviour** and other needed details are provided.
- [x] Feature requests contain a **description** of the feature
you're requesting as well as a brief **scenario** explaining
under what circumstances this might be useful.

JCenter is deprecated and will allow to download until feb 1st 2022 as stated here https://developer.android.com/studio/build/jcenter-migration

Any plan to migrate elsewhere? maven or jitpack?

**Comment by aenonGit** [comment]
nevermind, we could always use github as dependency

**Comment by ZenDeveloper7** [comment]
What's the new dependency? I removed jcenter() from my project and now I can't resolve the library @aenonGit

**Comment by aenonGit** [comment]
https://stackoverflow.com/questions/18748436/is-it-possible-to-declare-git-repository-as-dependency-in-android-gradle

**Comment by ZenDeveloper7** [comment]
> https://stackoverflow.com/questions/18748436/is-it-possible-to-declare-git-repository-as-dependency-in-android-gradle

Thanks!
